stages:
  - publish

publish:
  image: node:16
  stage: publish
  tags:
    - moreillon
  script:
    # Install dependencies and build app
    - npm install
    - npm run build
    # Auth and publish to NPM
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish --access=public
